services:
  hadoop-master:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-master
    ports:
      - "9870:9870"
      - "8088:8088"
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-master:9000
    networks:
      - hadoop-net

  hadoop-worker1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-worker1
    environment:
      - SERVICE_PRECONDITION=hadoop-master:9870
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-master:9000
    networks:
      - hadoop-net

  hadoop-worker2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-worker2
    environment:
      - SERVICE_PRECONDITION=hadoop-master:9870
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-master:9000
    networks:
      - hadoop-net

networks:
  hadoop-net:
    driver: bridge